In [1]:
import pandas as pd
df = pd.read_csv("books.csv")
df.head(10)

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count
0,9780002005883,0002005883,Gilead,NaN,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0
1,9780002261982,0002261987,Spider's Web,A Novel,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0
2,9780006163831,0006163831,The One Tree,NaN,Stephen R. Donaldson,American fiction,http://books.google.com/books/content?id=OmQaw...,Volume Two of Stephen Donaldson's acclaimed se...,1982.0,3.97,479.0,172.0
3,9780006178736,0006178731,Rage of angels,NaN,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0
4,9780006280897,0006280897,The Four Loves,NaN,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0
5,9780006280934,0006280935,The Problem of Pain,NaN,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0
6,9780006353287,0006353282,An Autobiography,NaN,Agatha Christie,"Authors, English",http://books.google.com/books/content?id=c49GQ...,Donation.,1977.0,4.27,560.0,3975.0
7,9780006380832,0006380832,Empires of the Monsoon,A History of the Indian Ocean and Its Invaders,Richard Hall,"Africa, East",http://books.google.com/books/content?id=MuPEQ...,Until Vasco da Gama discovered the sea-route t...,1998.0,4.41,608.0,65.0
8,9780006470229,000647022X,The Gap Into Madness,Chaos and Order,Stephen R. Donaldson,"Hyland, Morn (Fictitious character)",http://books.google.com/books/content?id=4oXav...,A new-cover reissue of the fourth book in the ...,1994.0,4.15,743.0,103.0
9,9780006472612,0006472613,Master of the Game,NaN,Sidney Sheldon,Adventure stories,http://books.google.com/books/content?id=TkTYp...,Kate Blackwell is an enigma and one of the mos...,1982.0,4.11,489.0,43540.0

In [2]:
df.isnull().sum()

isbn13               0
isbn10               0
title                0
subtitle          4429
authors             72
categories          99
thumbnail          329
description        262
published_year       6
average_rating      43
num_pages           43
ratings_count       43
dtype: int64

In [3]:
df = df.dropna()

In [4]:
df.head()

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count
1,9780002261982,0002261987,Spider's Web,A Novel,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0
7,9780006380832,0006380832,Empires of the Monsoon,A History of the Indian Ocean and Its Invaders,Richard Hall,"Africa, East",http://books.google.com/books/content?id=MuPEQ...,Until Vasco da Gama discovered the sea-route t...,1998.0,4.41,608.0,65.0
8,9780006470229,000647022X,The Gap Into Madness,Chaos and Order,Stephen R. Donaldson,"Hyland, Morn (Fictitious character)",http://books.google.com/books/content?id=4oXav...,A new-cover reissue of the fourth book in the ...,1994.0,4.15,743.0,103.0
25,9780006499626,0006499627,Miss Marple,The Complete Short Stories,Agatha Christie,"Detective and mystery stories, English",http://books.google.com/books/content?id=a96qP...,"Miss Marple featured in 20 short stories, publ...",1997.0,4.20,359.0,6235.0
34,9780006551812,0006551815,'Tis,A Memoir,Frank McCourt,Ireland,http://books.google.com/books/content?id=Q3BhQ...,FROM THE PULIZER PRIZE-WINNING AUTHOR OF THE #...,2000.0,3.68,495.0,44179.0

In [5]:
df.isnull().sum()

isbn13            0
isbn10            0
title             0
subtitle          0
authors           0
categories        0
thumbnail         0
description       0
published_year    0
average_rating    0
num_pages         0
ratings_count     0
dtype: int64

In [6]:
df.reset_index(drop=True, inplace=True)
df.head()

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count
0,9780002261982,0002261987,Spider's Web,A Novel,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0
1,9780006380832,0006380832,Empires of the Monsoon,A History of the Indian Ocean and Its Invaders,Richard Hall,"Africa, East",http://books.google.com/books/content?id=MuPEQ...,Until Vasco da Gama discovered the sea-route t...,1998.0,4.41,608.0,65.0
2,9780006470229,000647022X,The Gap Into Madness,Chaos and Order,Stephen R. Donaldson,"Hyland, Morn (Fictitious character)",http://books.google.com/books/content?id=4oXav...,A new-cover reissue of the fourth book in the ...,1994.0,4.15,743.0,103.0
3,9780006499626,0006499627,Miss Marple,The Complete Short Stories,Agatha Christie,"Detective and mystery stories, English",http://books.google.com/books/content?id=a96qP...,"Miss Marple featured in 20 short stories, publ...",1997.0,4.20,359.0,6235.0
4,9780006551812,0006551815,'Tis,A Memoir,Frank McCourt,Ireland,http://books.google.com/books/content?id=Q3BhQ...,FROM THE PULIZER PRIZE-WINNING AUTHOR OF THE #...,2000.0,3.68,495.0,44179.0

In [7]:
from sentence_transformers import SentenceTransformer
import chromadb
from chromadb.utils import embedding_functions

In [8]:
df["search_text"] = (
    "Title: " + df["title"] + "| Author: " + df["authors"] + "| Categories: " + df["categories"] + "| Summary: " + df["description"]
)

In [9]:
df.head(10)

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,search_text
0,9780002261982,0002261987,Spider's Web,A Novel,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Title: Spider's Web| Author: Charles Osborne;A...
1,9780006380832,0006380832,Empires of the Monsoon,A History of the Indian Ocean and Its Invaders,Richard Hall,"Africa, East",http://books.google.com/books/content?id=MuPEQ...,Until Vasco da Gama discovered the sea-route t...,1998.0,4.41,608.0,65.0,Title: Empires of the Monsoon| Author: Richard...
2,9780006470229,000647022X,The Gap Into Madness,Chaos and Order,Stephen R. Donaldson,"Hyland, Morn (Fictitious character)",http://books.google.com/books/content?id=4oXav...,A new-cover reissue of the fourth book in the ...,1994.0,4.15,743.0,103.0,Title: The Gap Into Madness| Author: Stephen R...
3,9780006499626,0006499627,Miss Marple,The Complete Short Stories,Agatha Christie,"Detective and mystery stories, English",http://books.google.com/books/content?id=a96qP...,"Miss Marple featured in 20 short stories, publ...",1997.0,4.20,359.0,6235.0,Title: Miss Marple| Author: Agatha Christie| C...
4,9780006551812,0006551815,'Tis,A Memoir,Frank McCourt,Ireland,http://books.google.com/books/content?id=Q3BhQ...,FROM THE PULIZER PRIZE-WINNING AUTHOR OF THE #...,2000.0,3.68,495.0,44179.0,Title: 'Tis| Author: Frank McCourt| Categories...
5,9780006754893,0006754899,A Small Pinch of Weather,And Other Stories,Joan Aiken,"Children's stories, English",http://books.google.com/books/content?id=QiFhO...,A magical and fantastic collection of early st...,2000.0,4.27,239.0,116.0,Title: A Small Pinch of Weather| Author: Joan ...
6,9780007105045,0007105045,Tree and Leaf,The Homecoming of Beorhtnoth : Beorhthelm's Son,John Ronald Reuel Tolkien,Literary Collections,http://books.google.com/books/content?id=aPb_A...,"""The two works 'On fairy-stories' and 'Leaf by...",2001.0,4.09,176.0,2245.0,Title: Tree and Leaf| Author: John Ronald Reue...
7,9780007116263,0007116268,"The Lord of the Rings, the Return of the King",Visual Companion,Jude Fisher,Imaginary wars and battles,http://books.google.com/books/content?id=kNBnQ...,A visual guide to the third in the Lord of the...,2003.0,4.59,72.0,22.0,"Title: The Lord of the Rings, the Return of th..."
8,9780007135653,0007135653,The Lord of the Rings,The Art of The Return of the King,Gary Russell,Characters and characteristics in motion pictures,http://books.google.com/books/content?id=oEZ6A...,With complete access to artwork created over a...,2004.0,4.54,224.0,28.0,Title: The Lord of the Rings| Author: Gary Rus...
9,9780007137336,0007137338,Lirael,Daughter of the Clayr,Garth Nix,Fantasy fiction,http://books.google.com/books/content?id=sDzU8...,When a dangerous necromancer threatens to unle...,2004.0,4.30,527.0,1339.0,Title: Lirael| Author: Garth Nix| Categories: ...

In [10]:
df["search_text"]

0       Title: Spider's Web| Author: Charles Osborne;A...
1       Title: Empires of the Monsoon| Author: Richard...
2       Title: The Gap Into Madness| Author: Stephen R...
3       Title: Miss Marple| Author: Agatha Christie| C...
4       Title: 'Tis| Author: Frank McCourt| Categories...
                              ...
2177    Title: C.G. Jung and Hermann Hesse| Author: Mi...
2178    Title: How to Draw Manga| Author: Kazuko Tadan...
2179    Title: 日本語の感情表現集| Author: 村上真美子| Categories: F...
2180    Title: I Am that| Author: Sri Nisargadatta Mah...
2181    Title: 'I'm Telling You Stories'| Author: Hele...
Name: search_text, Length: 2182, dtype: str

In [12]:
model = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="all-MiniLM-L6-v2")
client = chromadb.PersistentClient(path="./book_vector_db")
collection = client.get_or_create_collection(name="new_book_catalog", embedding_function=model)

In [13]:
collection.count()

0

In [14]:
collection

Collection(name=new_book_catalog)

In [15]:
p = df["search_text"].tolist()
p

["Title: Spider's Web| Author: Charles Osborne;Agatha Christie| Categories: Detective and mystery stories| Summary: A new 'Christie for Christmas' -- a full-length novel adapted from her acclaimed play by Charles Osborne Following BLACK COFFEE and THE UNEXPECTED GUEST comes the final Agatha Christie play novelisation, bringing her superb storytelling to a new legion of fans. Clarissa, the wife of a Foreign Office diplomat, is given to daydreaming. 'Supposing I were to come down one morning and find a dead body in the library, what should I do?' she muses. Clarissa has her chance to find out when she discovers a body in the drawing-room of her house in Kent. Desperate to dispose of the body before her husband comes home with an important foreign politician, Clarissa persuades her three house guests to become accessories and accomplices. It seems that the murdered man was not unknown to certain members of the house party (but which ones?), and the search begins for the murderer and the motive, while at the same time trying to persuade a police inspector that there has been no murder at all... SPIDER'S WEB was written in 1954 specifically for Margaret Lockwood and opened first at the Theatre Royal Nottingham before moving to the Savoy Theatre in London on 14 December 1954. With THE MOUSETRAP and WI",
 "Title: Empires of the Monsoon| Author: Richard Hall| Categories: Africa, East| Summary: Until Vasco da Gama discovered the sea-route to the East in 1497-9 almost nothing was known in the West of the exotic cultures and wealth of the Indian Ocean and its peoples. It is this civilization and its destruction at the hands of the West that Richard Hall recreates in this book. Hall's history of the exploration and exploitation by Chinese and Arab travellers, and by the Portuguese, Dutch and British alike is one of brutality, betrayal and colonial ambition.",
 "Title: The Gap Into Madness| Author: Stephen R. Donaldson| Categories: Hyland, Morn (Fictitious character)| Summary: A new-cover reissue of the fourth book in the bestselling five-volume sf series created by the world-famous author of the Thomas Covenant chronicles -- and acclaimed as the 'best work of his career'. Events were not moving as the Amnion had intended. Once again humans had been false in their dealings with the aliens. As the planetoid Thanatos Minor exploded into atoms, the Trumpet hurtled into space only one step ahead of hostile pursuers. On board were Morn Hyland and her force-grown son Davies, cyborg Angus Thermopyle and Captain Nick Succorso -- old enemies thrown together in a desperate bid for survival. For both the Amnion and the UMCP, the immediate capture of the fleeing ship and the secrets it contained was imperative. But for Trumpet's exhausted crew the only hope lay in an illegal lab in the distant binary solar system of Valdor Industrial. It would be a journey of unpredictable danger -- from which not all would return...",
 'Title: Miss Marple| Author: Agatha Christie| Categories: Detective and mystery stories, English| Summary: Miss Marple featured in 20 short stories, published in a number of different collections in Britain and America. Presented here in their order of publication, Miss Marple uses her unique insight to deduce the truth about a series of unsolved crimes.',
 'Title: \'Tis| Author: Frank McCourt| Categories: Ireland| Summary: FROM THE PULIZER PRIZE-WINNING AUTHOR OF THE #1 "NEW YORK TIMES" BESTSELLER "ANGELA\'S ASHES" Frank McCourt\'s glorious childhood memoir, "Angela\'s Ashes, " has been loved and celebrated by readers everywhere. It won the National Book Critics Circle Award, the "Los Angeles Times" Book Award and the Pulitzer Prize. Rarely has a book so swiftly found its place on the literary landscape. And now we have "\'Tis, " the story of Frank\'s American journey from impoverished immigrant to brilliant teacher and raconteur. Frank lands in New York at age nineteen and gets a job at the Biltmore Hotel, where he immediately encounters the vivid hierarchies of this "classless country," and then is drafted into the army and is sent to Germany to train dogs and type reports. It is Frank\'s incomparable voice that renders these experiences spellbinding. When Frank returns to America in 1953, he works on the docks, always resisting what everyone tells him. He knows that he should be getting an education, and though he left school at fourteen, he talks his way into New York University. There, he falls in love with the quintessential Yankee and tries to live his dream. But it is not until he starts to teach that Frank finds his place in the world.',
 "Title: A Small Pinch of Weather| Author: Joan Aiken| Categories: Children's stories, English| Summary: A magical and fantastic collection of early stories by one of the most original children's authors of the 20th century. For 8-11 year olds.",
 'Title: Tree and Leaf| Author: John Ronald Reuel Tolkien| Categories: Literary Collections| Summary: "The two works \'On fairy-stories\' and \'Leaf by Niggle\' were first brought together to form the book \'Tree and leaf\' in 1964. In this new edition a third element is added: the poem Mythopoeia, the making of myths..."--Preface.',
 'Title: The Lord of the Rings, the Return of the King| Author: Jude Fisher| Categories: Imaginary wars and battles| Summary: A visual guide to the third in the Lord of the Rings movie trilogy. A large-format, full-colour guide to the characters, places, landscapes, artefacts, battles, and costumes as seen in the film, it features images, informative text and specially commissioned extras.',
 "Title: The Lord of the Rings| Author: Gary Russell| Categories: Characters and characteristics in motion pictures| Summary: With complete access to artwork created over a five-year period, this guide illustrates the creative development of The Return of the King. It contains over 600 images, from the earliest pencil sketches and conceptual drawings to magnificent paintings, sculptures and digital imagery that shaped the look of the film. Contributing artists include John Howe and Alan Lee, artists who have inspired Peter Jackson's vision of Middle-earth and worked with him to bring the trilogy to the big screen. Peter Jackson himself provides the afterword in which he discusses the importance of the conceptual art to the film. It covers most aspects of the eagerly awaited finale to the enormously successful trilogy, from locations and costumes to weaponry and creatures. The artists who created all of these diverse elements explain how they contributed to the development of the film.",
 'Title: Lirael| Author: Garth Nix| Categories: Fantasy fiction| Summary: When a dangerous necromancer threatens to unleash a long-buried evil, Lirael and Prince Sameth are drawn into a battle to save the Old Kingdom and reveal their true destinies. Suggested level: secondary.',
 "Title: Breaking Open the Head| Author: Daniel Pinchbeck| Categories: Hallucinogenic drugs| Summary: A new 'The Doors of Perception' for the 21st century? A visionary journey from cynicism to shamanism by a brilliant young US writer.",
 'Title: The Yiddish Policemen\'s Union| Author: Michael Chabon| Categories: Fiction| Summary: For sixty years, Jewish refugees and their descendants have prospered in the Federal District of Sitka, a "temporary" safe haven created in the wake of revelations of the Holocaust and the shocking 1948 collapse of the fledgling state of Israel. Proud, grateful, and longing to be American, the Jews of the Sitka District have created their own little world in the Alaskan panhandle, a vibrant, gritty, soulful, and complex frontier city that moves to the music of Yiddish. For sixty years they have been left alone, neglected and half-forgotten in a backwater of history. Now the District is set to revert to Alaskan control, and their dream is coming to an end: once again the tides of history threaten to sweep them up and carry them off into the unknown. But homicide detective Meyer Landsman of the District Police has enough problems without worrying about the upcoming Reversion. His life is a shambles, his marriage a wreck, his career a disaster. He and his half-Tlingit partner, Berko Shemets, can\'t catch a break in any of their outstanding cases. Landsman\'s new supervisor is the love of his life—and also his worst nightmare. And in the cheap hotel where he has washed up, someone has just committed a murder—right under Landsman\'s nose. Out of habit, obligation, and a mysterious sense that it somehow offers him a shot at redeeming himself, Landsman begins to investigate the killing of his neighbor, a former chess prodigy. But when word comes down from on high that the case is to be dropped immediately, Landsman soon finds himself contending with all the powerful forces of faith, obsession, hopefulness, evil, and salvation that are his heritage—and with the unfinished business of his marriage to Bina Gelbfish, the one person who understands his darkest fears. At once a gripping whodunit, a love story, an homage to 1940s noir, and an exploration of the mysteries of exile and redemption, The Yiddish Policemen\'s Union is a novel only Michael Chabon could have written.',
 "Title: The Return of the King| Author: J. R. R. Tolkien| Categories: Baggins, Frodo (Fictitious character)| Summary: THE GREATEST FANTASY EPIC OF OUR TIME While the evil might of the Dark Lord Sauron swarmed out to conquer all Middle-earth, Frodo and Sam struggled deep into Mordor, seat of Sauron's power. To defeat the Dark Lord, the accursed Ring of Power had to be destroyed in the fires of Mount Doom. But the way was impossibly hard, and Frodo was weakening. Weighed down by the compulsion of the Ring he began finally to despair. The awesome conclusion of J.R.R. Tolkien's The Lord of the Rings, beloved by millions of readers around the world.",
 "Title: Poirot| Author: Agatha Christie| Categories: Authors| Summary: The final POIROT omnibus, featuring the last four appearances of the detective's side-kick, the sleuthing crime novelist Ariadne Oliver: Third Girl, Hallowe'en Party, Elephants Can Remember and The Pale Horse. Poirot and Mrs Oliver continue their sleuthing in the 1960s in four uncharacteristically 'modern' novels with an added twist of danger...Third Girl Poirot finally admits he is growing old as a perplexed girl thinks she may have killed someone. Here Christie dragged Poirot into the swinging 60s and effectively squared him up against a world featuring sex, drugs and hippies. Hallowe'en Party A teenage murder witness is drowned in a tub of apples. This was only the second time Christie wrote about the death of a child, and is all the more engrossing for it. Elephants Can Remember An old husband and wife double murder has never been solved -- until now. This was the very last Poirot story that Agatha Christie wrote, and garnered good reviews. The Pale Horse A priest's death leads to sinister goings-on in an old country inn. This bonus novel featured Mrs Oliver for once without Poirot and was one of Christie's darkest stories, blending witchcraft and murder.",
 'Title: Discover Your Destiny with the Monk Who Sold His Ferrari| Author: Robin Sharma| Categories: Conduct of life| Summary: A potent pathway to self-awakening that will help you to live your greatest life and claim the happiness, prosperity and inner peace that you deserve. From the author of the international bestseller, The Monk Who Sold His Ferrari.',
 "Title: Naked Lunch| Author: William S. Burroughs| Categories: Alienation (Social psychology)| Summary: The anarchic, phenomenally strong-selling classic from the godfather of the Beats: revitalised with a cool new jacket. WELCOME TO INTERZONE...Say hello to Bradley the Buyer, the best narcotics agent in the business. Attend international playboy A.J.'s annual party, where the punch is to be treated with extreme caution. Meet Dr 'Fingers' Schafer, the Lobotomy Kid and his giant centipede, 'The Complete American De-anxietized Man.' And enter the dark and infernal mind of Bill Lee as he pursues his daily quest for the ultimate merchandise...Provocative, influential, morbidly fascinating, Naked Lunch is an apocalyptic ride through the darker recesses of the human psyche.",
 'Title: Close Range| Author: Annie Proulx| Categories: Cowboys| Summary: The title story in this collection of shorts now a film from Ang Lee.',
 'Title: The Love of the Last Tycoon| Author: F. Scott Fitzgerald| Categories: Fiction| Summary: Depicts the inner-workings of the Hollywood movie industry and its impact on the fabric of American life.',
 "Title: Tyranny of the Majority| Author: Lani Guinier| Categories: History| Summary: At last...the public hearing she was denied...These essays reveal keen powers of analysis applied to some of the most obdurate problems that bedevil electoral politics. Anyone who cares about the mechanisms of democracy should be engaged by her tough-minded explorations. It doesn't matter where you think you stand: it's all here, to argue or agree with. -- Henry Louis Gates, Jr. Lani Guinier's fascinating book is a prophetic intervention into a public conversation we desperately need to rejuvenate. There is no doubt that her powerful voice will produce good consequences for our nation and world. -- Cornel West, Author of Race Matters Intriguing and desperately needed... -- The San Francisco Chronicle",
 'Title: Presidential Power and the Modern Presidents| Author: Richard E. Neustadt| Categories: History| Summary: Suggests a theory of presidential power, and tests it against the events in the administrations of the postwar presidents',
 "Title: Where the Red Fern Grows| Author: Wilson Rawls| Categories: Juvenile Fiction| Summary: A young boy living in the Ozarks achieves his heart's desire when he becomes the owner of two redbone hounds and teaches them to be champion hunters.",
 "Title: How to Read Literature Like a Professor| Author: Thomas C. Foster| Categories: Literary Criticism| Summary: What does it mean when a fictional hero takes a journey?. Shares a meal? Gets drenched in a sudden rain shower? Often, there is much more going on in a novel or poem than is readily visible on the surface—a symbol, maybe, that remains elusive, or an unexpected twist on a character—and there's that sneaking suspicion that the deeper meaning of a literary text keeps escaping you. In this practical and amusing guide to literature, Thomas C. Foster shows how easy and gratifying it is to unlock those hidden truths, and to discover a world where a road leads to a quest; a shared meal may signify a communion; and rain, whether cleansing or destructive, is never just rain. Ranging from major themes to literary models, narrative devices, and form, How to Read Literature Like a Professor is the perfect companion for making your reading experience more enriching, satisfying, and fun.",
 "Title: Going Postal| Author: Terry Pratchett| Categories: Fiction| Summary: Arch-swindler Moist Van Lipwig never believed his confidence crimes were hanging offenses -- until he found himself with a noose tightly around his neck, dropping through a trapdoor, and falling into ... a government job? By all rights, Moist should have met his maker. Instead, it's Lord Vetinari, supreme ruler of Ankh-Morpork, who promptly offers him a job as Postmaster. Since his only other option is a nonliving one, Moist accepts the position -- and the hulking golem watchdog who comes along with it, just in case Moist was considering abandoning his responsibilities prematurely. Getting the moribund Postal Service up and running again, however, may be a near-impossible task, what with literally mountains of decades-old undelivered mail clogging every nook and cranny of the broken-down post office building; and with only a few creaky old postmen and one rather unstable, pin-obsessed youth available to deliver it. Worse still, Moist could swear the mail is talking to him. Worst of all, it means taking on the gargantuan, money-hungry Grand Trunk clacks communication monopoly and its bloodthirsty piratical head, Mr. Reacher Gilt. But it says on the building neither rain nor snow nor glo m of ni t ... Inspiring words (admittedly, some of the bronze letters have been stolen), and for once in his wretched life Moist is going to fight. And if the bold and impossible are what's called for, he'll do it -- in order to move the mail, continue breathing, get the girl, and specially deliver that invaluable commodity that every human being (not to mention troll, dwarf, and, yes, even golem) requires: hope.",
 'Title: Modern Mind| Author: Peter Watson| Categories: Science| Summary: From Freud to Babbitt, from Animal Farm to Sartre to the Great Society, from the Theory of Relativity to counterculture to Kosovo, The Modern Mind is encyclopedic, covering the major writers, artists, scientists, and philosophers who produced the ideas by which we live. Peter Watson has produced a fluent and engaging narrative of the intellectual tradition of the twentieth century, and the men and women who created it.',
 'Title: A Year in the Life of William Shakespeare| Author: James Shapiro| Categories: Biography & Autobiography| Summary: 1599 was an epochal year for Shakespeare and England Shakespeare wrote four of his most famous plays: Henry the Fifth, Julius Caesar, As You Like It, and, most remarkably, Hamlet; Elizabethans sent off an army to crush an Irish rebellion, weathered an Armada threat from Spain, gambled on a fledgling East India Company, and waited to see who would succeed their aging and childless queen. James Shapiro illuminates both Shakespeare’s staggering achievement and what Elizabethans experienced in the course of 1599, bringing together the news and the intrigue of the times with a wonderful evocation of how Shakespeare worked as an actor, businessman, and playwright. The result is an exceptionally immediate and gripping account of an inspiring moment in history.',
 'Title: The Bromeliad Trilogy| Author: Terry Pratchett| Categories: Juvenile Fiction| Summary: In a world whose seasons are defined by Christmas sales and Spring Fashions, hundreds of tiny nomes live in the corners and crannies of a human-run department store. They have made their homes beneath the floorboards for generations and no longer remember -- or even believe in -- life beyond the Store walls. Until the day a small band of nomes arrives at the Store from the Outside. Led by a young nome named Masklin, the Outsiders carry a mysterious black box (called the Thing), and they deliver devastating news: In twenty-one days, the Store will be destroyed. Now all the nomes must learn to work together, and they must learn to think -- and to think BIG. Part satire, part parable, and part adventure story par excellence, master storyteller Terry Pratchett’s engaging trilogy traces the nomes’ flight and search for safety, a search that leads them to discover their own astonishing origins and takes them beyond their wildest dreams.',

In [16]:
if collection.count() == 0:
    print("Embedding getting ready...")
    
    collection.add(
        ids=[str(i) for i in df.index],
        
        documents=df["search_text"].tolist(),
        metadatas=df[['title', 'authors', 'average_rating']].to_dict(orient='records')
    )
    print("Database = ready")

Embedding getting ready...
Database = ready

In [17]:
collection.count()

2182

In [18]:
vs=df[['title', 'authors', 'average_rating']].to_dict(orient='records')
vs

[{'title': "Spider's Web",
  'authors': 'Charles Osborne;Agatha Christie',
  'average_rating': 3.83},
 {'title': 'Empires of the Monsoon',
  'authors': 'Richard Hall',
  'average_rating': 4.41},
 {'title': 'The Gap Into Madness',
  'authors': 'Stephen R. Donaldson',
  'average_rating': 4.15},
 {'title': 'Miss Marple', 'authors': 'Agatha Christie', 'average_rating': 4.2},
 {'title': "'Tis", 'authors': 'Frank McCourt', 'average_rating': 3.68},
 {'title': 'A Small Pinch of Weather',
  'authors': 'Joan Aiken',
  'average_rating': 4.27},
 {'title': 'Tree and Leaf',
  'authors': 'John Ronald Reuel Tolkien',
  'average_rating': 4.09},
 {'title': 'The Lord of the Rings, the Return of the King',
  'authors': 'Jude Fisher',
  'average_rating': 4.59},
 {'title': 'The Lord of the Rings',
  'authors': 'Gary Russell',
  'average_rating': 4.54},
 {'title': 'Lirael', 'authors': 'Garth Nix', 'average_rating': 4.3},
 {'title': 'Breaking Open the Head',
  'authors': 'Daniel Pinchbeck',
  'average_rating': 4.06},
 {'title': "The Yiddish Policemen's Union",
  'authors': 'Michael Chabon',
  'average_rating': 3.7},
 {'title': 'The Return of the King',
  'authors': 'J. R. R. Tolkien',
  'average_rating': 4.52},
 {'title': 'Poirot', 'authors': 'Agatha Christie', 'average_rating': 4.2},
 {'title': 'Discover Your Destiny with the Monk Who Sold His Ferrari',
  'authors': 'Robin Sharma',
  'average_rating': 3.9},
 {'title': 'Naked Lunch',
  'authors': 'William S. Burroughs',
  'average_rating': 3.44},
 {'title': 'Close Range', 'authors': 'Annie Proulx', 'average_rating': 3.99},
 {'title': 'The Love of the Last Tycoon',
  'authors': 'F. Scott Fitzgerald',
  'average_rating': 3.65},
 {'title': 'Tyranny of the Majority',
  'authors': 'Lani Guinier',
  'average_rating': 3.82},
 {'title': 'Presidential Power and the Modern Presidents',
  'authors': 'Richard E. Neustadt',
  'average_rating': 3.79},
 {'title': 'Where the Red Fern Grows',
  'authors': 'Wilson Rawls',
  'average_rating': 4.37},
 {'title': 'How to Read Literature Like a Professor',
  'authors': 'Thomas C. Foster',
  'average_rating': 3.65},
 {'title': 'Going Postal',
  'authors': 'Terry Pratchett',
  'average_rating': 4.38},
 {'title': 'Modern Mind', 'authors': 'Peter Watson', 'average_rating': 4.27},
 {'title': 'A Year in the Life of William Shakespeare',
  'authors': 'James Shapiro',
  'average_rating': 4.09},
 {'title': 'The Bromeliad Trilogy',
  'authors': 'Terry Pratchett',
  'average_rating': 4.06},
 {'title': 'Identity', 'authors': 'Milan Kundera', 'average_rating': 3.68},
 {'title': 'The thief of always',
  'authors': 'Clive Barker',
  'average_rating': 4.19},
 {'title': 'The Illustrated Alchemist',
  'authors': 'Paulo Coelho;Alan R. Clarke;Moebius',
  'average_rating': 3.85},
 {'title': 'Mars and Venus Book of Days',
  'authors': 'John Gray',
  'average_rating': 3.54},
 {'title': 'The Secret Garden Cookbook',
  'authors': 'Amy Cotler',
  'average_rating': 4.28},
 {'title': "Laura's Album",
  'authors': 'William Anderson',
  'average_rating': 4.3},
 {'title': 'Small Wonder',
  'authors': 'Barbara Kingsolver',
  'average_rating': 4.01},
 {'title': 'Worlds Enough & Time',
  'authors': 'Dan Simmons',
  'average_rating': 3.75},
 {'title': 'The Cheese Monkeys',
  'authors': 'Chip Kidd',
  'average_rating': 3.75},
 {'title': 'Caesar', 'authors': 'Colleen McCullough', 'average_rating': 4.36},
 {'title': 'Fragile Things', 'authors': 'Neil Gaiman', 'average_rating': 4.01},
 {'title': 'What Went Wrong?',
  'authors': 'Bernard Lewis',
  'average_rating': 3.49},
 {'title': 'Letters from the Earth',
  'authors': 'Mark Twain',
  'average_rating': 4.22},
 {'title': 'Savannah Blues',
  'authors': 'Mary Kay Andrews',
  'average_rating': 3.98},
 {'title': "The Innovator's Dilemma",
  'authors': 'Clayton M. Christensen',
  'average_rating': 3.99},
 {'title': 'Happiness', 'authors': 'Will Ferguson', 'average_rating': 3.78},
 {'title': 'Warrior of the Light',
  'authors': 'Paulo Coelho',
  'average_rating': 3.7},
 {'title': 'The Devil and Miss Prym',
  'authors': 'Paulo Coelho',
  'average_rating': 3.6},
 {'title': 'The Big Bing', 'authors': 'Stanley Bing', 'average_rating': 3.08},
 {'title': 'Walt Whitman', 'authors': 'Justin Kaplan', 'average_rating': 3.99},
 {'title': 'How to Make Love Like a Porn Star',
  'authors': 'Jenna Jameson;Neil Strauss',
  'average_rating': 3.75},
 {'title': '1421', 'authors': 'Gavin Menzies', 'average_rating': 3.59},
 {'title': 'The Girls of Lighthouse Lane #3',
  'authors': 'Thomas Kinkade;Erika Tamar',
  'average_rating': 3.96},
 {'title': 'The Bradbury Chronicles',
  'authors': 'Sam Weller',
  'average_rating': 4.22},
 {'title': 'The Wicked Day',
  'authors': 'Mary Stewart',
  'average_rating': 4.09},
 {'title': 'The Game', 'authors': 'Neil Strauss', 'average_rating': 3.74},
 {'title': 'Gold', 'authors': 'Isaac Asimov', 'average_rating': 3.99},
 {'title': 'Built to Last',
  'authors': 'Jim Collins;Jerry I. Porras',
  'average_rating': 3.98},
 {'title': 'Fluke', 'authors': 'Christopher Moore', 'average_rating': 3.75},
 {'title': 'A Crack in the Edge of the World',
  'authors': 'Simon Winchester',
  'average_rating': 3.78},
 {'title': 'Men Are from Mars, Women Are from Venus',
  'authors': 'John Gray',
  'average_rating': 3.54},
 {'title': 'Slouching Toward Nirvana',
  'authors': 'Charles Bukowski',
  'average_rating': 3.99},
 {'title': 'Bad Childhood---Good Life',
  'authors': 'Laura Schlessinger',
  'average_rating': 3.92},
 {'title': 'Cat Cross Their Graves',
  'authors': 'Shirley Rousseau Murphy',
  'average_rating': 4.3},
 {'title': 'Cat Breaking Free',
  'authors': 'Shirley Rousseau Murphy',
  'average_rating': 4.2},
 {'title': 'Slider', 'authors': 'Patrick Robinson', 'average_rating': 4.18},
 {'title': 'The Black Dahlia Files',
  'authors': 'Don Wolfe',
  'average_rating': 3.84},
 {'title': 'Eleven Minutes',
  'authors': 'Paulo Coelho',
  'average_rating': 3.69},
 {'title': 'Zen and the Art of Motorcycle Maintenance',
  'authors': 'Robert M. Pirsig',
  'average_rating': 3.77},
 {'title': 'Ulysses S. Grant',
  'authors': 'Michael Korda',
  'average_rating': 3.88},
 {'title': 'A Dirty Job',
  'authors': 'Christopher Moore',
  'average_rating': 4.07},
 {'title': 'Quicksilver',
  'authors': 'Neal Stephenson',
  'average_rating': 3.93},
 {'title': 'Every Book Its Reader',
  'authors': 'Nicholas A. Basbanes',
  'average_rating': 3.96},
 {'title': 'Lost Horizon', 'authors': 'James Hilton', 'average_rating': 3.92},
 {'title': 'Thomas Jefferson',
  'authors': 'Christopher Hitchens',
  'average_rating': 3.92},
 {'title': 'Muhammad', 'authors': 'Karen Armstrong', 'average_rating': 4.04},
 {'title': 'Meeting Jesus Again for the First Time',
  'authors': 'Marcus J. Borg',
  'average_rating': 4.14},
 {'title': 'Reading the Bible Again for the First Time',
  'authors': 'Marcus J. Borg',
  'average_rating': 4.13},
 {'title': 'Shadow of the Almighty',
  'authors': 'Elisabeth Elliot',
  'average_rating': 4.39},
 {'title': 'C.S. Lewis', 'authors': 'C. S. Lewis', 'average_rating': 4.31},
 {'title': 'Learning to Love',
  'authors': 'Thomas Merton',
  'average_rating': 4.5},
 {'title': 'Cash', 'authors': 'Johnny Cash', 'average_rating': 4.07},
 {'title': 'The Collected Letters of C.S. Lewis, Volume 1',
  'authors': 'C. S. Lewis',
  'average_rating': 4.37},
 {'title': 'Touching the Void',
  'authors': 'Joe Simpson',
  'average_rating': 4.21},
 {'title': 'Anybody Out There?',
  'authors': 'Marian Keyes',
  'average_rating': 3.91},
 {'title': 'The Confusion',
  'authors': 'Neal Stephenson',
  'average_rating': 4.25},
 {'title': 'Behind the Curtain',
  'authors': 'Peter Abrahams',
  'average_rating': 3.9},
 {'title': 'Wicked Musical Tie-in Edition',
  'authors': 'Gregory Maguire',
  'average_rating': 3.53},
 {'title': 'Son of a Witch',
  'authors': 'Gregory Maguire',
  'average_rating': 3.47},
 {'title': 'Beauty', 'authors': 'Robin McKinley', 'average_rating': 4.05},
 {'title': 'Mating in Captivity',
  'authors': 'Esther Perel',
  'average_rating': 4.13},
 {'title': 'Forgotten New York',
  'authors': 'Kevin Walsh',
  'average_rating': 4.18},
 {'title': 'The Dead Beat',
  'authors': 'Marilyn Johnson',
  'average_rating': 3.41},
 {'title': 'The Reading Group',
  'authors': 'Elizabeth Noble',
  'average_rating': 3.34},
 {'title': "YOU: The Owner's Manual",
  'authors': 'Michael F Roizen;Mehmet C Oz',
  'average_rating': 3.82},
 {'title': 'The Final Solution',
  'authors': 'Michael Chabon',
  'average_rating': 3.31},
 {'title': "The Cat's Pajamas",
  'authors': 'Ray Bradbury',
  'average_rating': 3.73},
 {'title': 'Holy Skirts', 'authors': 'Rene Steinke', 'average_rating': 3.61},
 {'title': 'A False Mirror',
  'authors': 'Charles Todd',
  'average_rating': 4.02},
 {'title': 'Cracks in My Foundation',
  'authors': 'Marian Keyes',
  'average_rating': 3.81},
 {'title': 'Mysteries of Pittsburgh',
  'authors': 'Michael Chabon',
  'average_rating': 3.64},
 {'title': 'Everything Is Illuminated tie-in',
  'authors': 'Jonathan Safran Foer',
  'average_rating': 3.9},
 {'title': 'Flight of the Nighthawks',
  'authors': 'Raymond E. Feist',
  'average_rating': 3.95},
 {'title': 'Into a Dark Realm',
  'authors': 'Raymond E. Feist',
  'average_rating': 4.0},
 {'title': 'Last of the Wilds',
  'authors': 'Trudi Canavan',
  'average_rating': 4.03},
 {'title': 'Voice of the Gods',
  'authors': 'Trudi Canavan',
  'average_rating': 4.08},
 {'title': 'Missing Mom',
  'authors': 'Joyce Carol Oates',
  'average_rating': 3.54},
 {'title': 'The Collected Letters of C.S. Lewis, Volume 3',
  'authors': 'C. S. Lewis',
  'average_rating': 4.49},
 {'title': 'King of the Vagabonds',
  'authors': 'Neal Stephenson',
  'average_rating': 4.16},
 {'title': 'Odalisque', 'authors': 'Neal Stephenson', 'average_rating': 4.2},
 {'title': 'Black Boy', 'authors': 'Richard Wright', 'average_rating': 4.05},
 {'title': 'Rat Bastards', 'authors': 'John Shea', 'average_rating': 3.51},
 {'title': 'The Last Days of Henry VIII',
  'authors': 'Robert Hutchinson',
  'average_rating': 4.14},
 {'title': 'Krakatoa', 'authors': 'Simon Winchester', 'average_rating': 3.87},
 {'title': 'The Professor and the Madman',
  'authors': 'Simon Winchester',
  'average_rating': 3.84},
 {'title': 'The Curtain', 'authors': 'Milan Kundera', 'average_rating': 3.96},
 {'title': "A Hard Day's Write, 3e",
  'authors': 'Steve Turner',
  'average_rating': 4.18},
 {'title': 'Mambo Kings Play Songs of Love, The Tie-in',
  'authors': 'Oscar Hijuelos',
  'average_rating': 3.68},
 {'title': 'Sex with the Queen',
  'authors': 'Eleanor Herman',
  'average_rating': 3.91},
 {'title': 'Queen of Babble', 'authors': 'Meg Cabot', 'average_rating': 3.69},
 {'title': 'Animal, Vegetable, Miracle',
  'authors': 'Barbara Kingsolver;Camille Kingsolver;Steven L. Hopp',
  'average_rating': 4.04},
 {'title': 'Good Omens',
  'authors': 'Neil Gaiman;Terry Pratchett',
  'average_rating': 4.25},
 {'title': 'Pretty Things', 'authors': 'Liz Goldwyn', 'average_rating': 4.31},
 {'title': 'Genome', 'authors': 'Matt Ridley', 'average_rating': 4.03},
 {'title': 'The Zero', 'authors': 'Jess Walter', 'average_rating': 3.5},
 {'title': 'Kitchen Confidential Updated Ed',
  'authors': 'Anthony Bourdain',
  'average_rating': 4.06},
 {'title': 'Teaching a Stone to Talk',
  'authors': 'Annie Dillard',
  'average_rating': 4.2},
 {'title': 'The Dance of Intimacy',
  'authors': 'Harriet Lerner',
  'average_rating': 4.06},
 {'title': 'Tell My Horse',
  'authors': 'Zora Neale Hurston',
  'average_rating': 3.97},
 {'title': 'The Lost Continent',
  'authors': 'Bill Bryson',
  'average_rating': 3.83},
 {'title': 'Three by Annie Dillard',
  'authors': 'Annie Dillard',
  'average_rating': 4.34},
 {'title': 'Declarations of Independence',
  'authors': 'Howard Zinn',
  'average_rating': 4.26},
 {'title': 'The Infinite Plan',
  'authors': 'Isabel Allende',
  'average_rating': 3.71},
 {'title': 'The Throne of the Third Heaven of the Nations Millennium General Assembly',
  'authors': 'Denis Johnson',
  'average_rating': 4.16},
 {'title': 'Testaments Betrayed',
  'authors': 'Milan Kundera',
  'average_rating': 4.04},
 {'title': 'Slowness', 'authors': 'Milan Kundera', 'average_rating': 3.66},
 {'title': 'As Nature Made Him',
  'authors': 'John Colapinto',
  'average_rating': 3.97},
 {'title': 'Identity', 'authors': 'Milan Kundera', 'average_rating': 3.68},
 {'title': 'The Poisonwood Bible',
  'authors': 'Barbara Kingsolver',
  'average_rating': 4.05},
 {'title': 'Cloudsplitter', 'authors': 'Russell Banks', 'average_rating': 3.9},
 {'title': 'Plato, Not Prozac!',
  'authors': 'Lou Marinoff',
  'average_rating': 3.39},
 {'title': 'The Map That Changed the World',
  'authors': 'Simon Winchester;Soun Vannithone',
  'average_rating': 3.82},
 {'title': 'A Mulligan for Bobby Jobe',
  'authors': 'Robert Cullen',
  'average_rating': 3.31},
 {'title': 'In the Footsteps of Mr. Kurtz',
  'authors': 'Michela Wrong',
  'average_rating': 3.98},
 {'title': 'Every Tongue Got to Confess',
  'authors': 'Zora Neale Hurston',
  'average_rating': 3.98},
 {'title': 'Kitchen Confidential',
  'authors': 'Anthony Bourdain',
  'average_rating': 4.06},
 {'title': 'One Matchless Time',
  'authors': 'Jay Parini',
  'average_rating': 3.97},
 {'title': 'The Girl in the Glass',
  'authors': 'Jeffrey Ford',
  'average_rating': 3.72},
 {'title': "Wittgenstein's Poker",
  'authors': 'David Edmonds;John Eidinow',
  'average_rating': 3.75},
 {'title': 'Smart Discipline(R)',
  'authors': 'Larry Koenig',
  'average_rating': 3.99},
 {'title': 'The Schopenhauer Cure',
  'authors': 'Irvin Yalom',
  'average_rating': 4.21},
 {'title': 'African Nights',
  'authors': 'Kuki Gallmann',
  'average_rating': 3.8},
 {'title': 'Beauty', 'authors': "John O'Donohue", 'average_rating': 4.45},
 {'title': 'The Darling', 'authors': 'Russell Banks', 'average_rating': 3.78},
 {'title': 'The Making of a Philosopher',
  'authors': 'Colin McGinn',
  'average_rating': 3.65},
 {'title': 'The Language Instinct',
  'authors': 'Steven Pinker',
  'average_rating': 4.05},
 {'title': 'Prodigal Summer',
  'authors': 'Barbara Kingsolver',
  'average_rating': 4.0},
 {'title': 'Fear of Falling',
  'authors': 'Barbara Ehrenreich',
  'average_rating': 3.9},
 {'title': 'Europe', 'authors': 'Norman Davies', 'average_rating': 4.17},
 {'title': 'Savage Inequalities',
  'authors': 'Jonathan Kozol',
  'average_rating': 4.24},
 {'title': 'Reasons to Live', 'authors': 'Amy Hempel', 'average_rating': 4.16},
 {'title': 'Courtesans and Fishcakes',
  'authors': 'James Davidson',
  'average_rating': 3.93},
 {'title': 'Confessions of an Ugly Stepsister',
  'authors': 'Gregory Maguire',
  'average_rating': 3.52},
 {'title': 'The Dirt',
  'authors': 'Tommy Lee;Vince Neil;Nikki Sixx;Mick Mars',
  'average_rating': 4.16},
 {'title': 'Cat Laughing Last',
  'authors': 'Shirley Rousseau Murphy',
  'average_rating': 4.21},
 {'title': 'Well of Darkness',
  'authors': 'Margaret Weis;Tracy Hickman',
  'average_rating': 3.66},
 {'title': 'Realms of Dragons',
  'authors': 'Margaret Weis;Denise Little;Tracy Hickman',
  'average_rating': 4.04},
 {'title': "Peril's Gate", 'authors': 'Janny Wurts', 'average_rating': 4.15},
 {'title': 'Cat on the Edge',
  'authors': 'Shirley Rousseau Murphy',
  'average_rating': 3.9},
 {'title': 'Cat in the Dark',
  'authors': 'Shirley Rousseau Murphy',
  'average_rating': 4.25},
 {'title': 'Homebody', 'authors': 'Orson Scott Card', 'average_rating': 3.39},
 {'title': 'Imajica II', 'authors': 'Clive Barker', 'average_rating': 4.42},
 {'title': 'Daughter of Fortune',
  'authors': 'Isabel Allende',
  'average_rating': 3.9},
 {'title': 'By the River Piedra I Sat Down and Wept',
  'authors': 'Paulo Coelho',
  'average_rating': 3.57},
 {'title': 'Veronika Decides to Die',
  'authors': 'Paulo Coelho',
  'average_rating': 3.7},
 {'title': 'Goodnight Moon 123',
  'authors': 'Margaret Wise Brown;Clement Hurd',
  'average_rating': 3.59},
 {'title': 'The Crusader', 'authors': 'Paul Kengor', 'average_rating': 4.2},
 {'title': "Spider's House", 'authors': 'Paul Bowles', 'average_rating': 4.03},
 {'title': 'Days', 'authors': 'Paul Bowles', 'average_rating': 3.3},
 {'title': 'Howl',
  'authors': 'Allen Ginsberg;Barry Miles',
  'average_rating': 4.22},
 {'title': 'When the Heart Waits',
  'authors': 'Sue Monk Kidd',
  'average_rating': 4.17},
 {'title': 'The Pact', 'authors': 'Jodi Picoult', 'average_rating': 4.01},
 {'title': 'Ines of My Soul LP',
  'authors': 'Isabel Allende',
  'average_rating': 3.92},
 {'title': 'My secret', 'authors': 'Frank Warren', 'average_rating': 4.34},
 {'title': 'The Secret Lives of Men and Women',
  'authors': 'Frank Warren',
  'average_rating': 4.37},
 {'title': 'The End of Days',
  'authors': 'Zecharia Sitchin',
  'average_rating': 4.06},
 {'title': 'Owning Your Own Shadow',
  'authors': 'Robert A. Johnson',
  'average_rating': 4.07},
 {'title': "The World's Religions",
  'authors': 'Huston Smith',
  'average_rating': 4.07},
 {'title': 'Rainforest Home Remedies',
  'authors': 'Rosita Arvigo;Nadine Epstein',
  'average_rating': 4.12},
 {'title': "Bulfinch's Mythology",
  'authors': 'Richard P. Martin',
  'average_rating': 4.1},
 {'title': 'The Wish Giver',
  'authors': 'Bill Brittain',
  'average_rating': 3.83},
 {'title': 'Child of the Owl',
  'authors': 'Laurence Yep',
  'average_rating': 3.6},
 {'title': "Dragon's Gate", 'authors': 'Laurence Yep', 'average_rating': 3.67},
 {'title': 'American Dragons',
  'authors': 'Laurence Yep',
  'average_rating': 3.41},
 {'title': 'Old Town in the Green Groves',
  'authors': 'Cynthia Rylant;Jim LaMarche',
  'average_rating': 4.04},
 {'title': 'My Little House Crafts Book',
  'authors': 'Carolyn Strom Collins',
  'average_rating': 4.05},
 {'title': 'Pioneer Girl',
  'authors': 'William Anderson',
  'average_rating': 4.15},
 {'title': 'What Would Machiavelli Do?',
  'authors': 'Stanley Bing',
  'average_rating': 3.46},
 {'title': 'Mission Possible',
  'authors': 'Ken Blanchard;Terry Waghorn',
  'average_rating': 3.42},
 {'title': 'Crucial Conversations',
  'authors': 'Kerry Patterson;Joseph Grenny;Ron McMillan;Al Switzler',
  'average_rating': 4.01},
 {'title': 'How to Talk to Anyone : 92 Little Tricks for Big Success in Relationships',
  'authors': 'Leil Lowndes',
  'average_rating': 3.78},
 {'title': 'Slim to None',
  'authors': 'Jennifer Hendricks',
  'average_rating': 3.65},
 {'title': 'The Last Dance',
  'authors': 'Lynne Ann DeSpelder;Albert Lee Strickland',
  'average_rating': 3.77},
 {'title': 'Who Moved My Cheese?',
  'authors': 'Spencer Johnson',
  'average_rating': 3.78},
 {'title': 'The Toy Maker',
  'authors': 'Anthony McReavy',
  'average_rating': 3.0},
 {'title': '"Surely You\'re Joking, Mr. Feynman!"',
  'authors': 'Richard Phillips Feynman;Ralph Leighton',
  'average_rating': 4.28},
 {'title': 'Blood and Gold', 'authors': 'Anne Rice', 'average_rating': 3.89},
 {'title': 'Bagombo Snuff Box',
  'authors': 'Kurt Vonnegut',
  'average_rating': 3.72},
 {'title': 'Operation Shylock',
  'authors': 'Philip Roth',
  'average_rating': 3.77},
 {'title': 'Fury', 'authors': 'Salman Rushdie', 'average_rating': 3.29},
 {'title': 'Yeats is Dead!',
  'authors': "Joseph O'Connor",
  'average_rating': 3.39},
 {'title': 'The Gangs of New York',
  'authors': 'Herbert Asbury',
  'average_rating': 3.59},
 {'title': 'Elephant', 'authors': 'Raymond Carver', 'average_rating': 4.11},
 {'title': 'Underground', 'authors': 'Haruki Murakami', 'average_rating': 3.9},
 {'title': 'Java', 'authors': 'Walter J. Savitch', 'average_rating': 3.86},
 {'title': 'Astronomy',
  'authors': 'Eric Chaisson;Stephen McMillan',
  'average_rating': 3.85},
 {'title': 'The Visual Arts',
  'authors': 'Hugh Honour;John Fleming',
  'average_rating': 3.82},
 {'title': 'Three Genres', 'authors': 'Stephen Minot', 'average_rating': 3.65},
 {'title': 'You Bright and Risen Angels',
  'authors': 'William T. Vollmann',
  'average_rating': 4.08},
 {'title': 'The Job',

In [19]:
def recommend_books(user_query, num_results=5):
    results = collection.query(
        query_texts = [user_query],
        n_results = num_results
        
    )
    print(f"\nTop {num_results} for: '{user_query}'")
    for i in range(num_results):
        res = results['metadatas'][0][i]
        score = results['distances'][0][i]
        print(f"- {res['title']} by {res['authors']} (Rating: {res['average_rating']}) [Dist: {round(score, 2)}]")

In [20]:
recommend_books("Detective and mystery stories")

Top 5 for: 'Detective and mystery stories'
- The New Annotated Sherlock Holmes by Arthur Conan Doyle (Rating: 4.63) [Dist: 0.48]
- Miss Marple by Agatha Christie (Rating: 4.2) [Dist: 0.48]
- The Various Haunts of Men by Susan Hill (Rating: 3.81) [Dist: 0.48]
- Filth by Irvine Welsh (Rating: 3.74) [Dist: 0.5]
- The Murders in the Rue Morgue by Edgar Allan Poe (Rating: 3.87) [Dist: 0.5]