In [1]:
import pandas as pd
df = pd.read_csv("loan_risk_prediction_dataset.csv")
df["DebtToIncomeRatio"] = df["LoanAmount"] / df["Income"]
df = df.dropna()
df

,Age,Income,LoanAmount,CreditScore,YearsExperience,Gender,Education,City,EmploymentType,LoanApproved,DebtToIncomeRatio
0,56,48353.0,31258.0,675.0,20,Female,High School,Houston,Unemployed,0,0.646454
1,69,57462.0,23262.0,586.0,6,Male,High School,San Francisco,Self-Employed,0,0.404824
2,46,44219.0,26530.0,781.0,26,Male,PhD,Houston,Self-Employed,1,0.599968
4,60,37034.0,27871.0,500.0,19,Female,High School,Chicago,Unemployed,0,0.752579
5,25,47886.0,18106.0,835.0,13,Male,Masters,New York,Salaried,1,0.378106
...,...,...,...,...,...,...,...,...,...,...,...
4992,66,45575.0,32748.0,803.0,39,Female,Masters,San Francisco,Salaried,1,0.718552
4994,21,40705.0,15668.0,396.0,34,Female,Bachelors,Houston,Unemployed,0,0.384916
4996,66,99146.0,9760.0,306.0,14,Male,PhD,New York,Unemployed,0,0.098441
4997,26,58100.0,18230.0,311.0,10,Female,High School,San Francisco,Self-Employed,0,0.313769
4998,53,58513.0,12373.0,813.0,23,Male,PhD,Houston,Salaried,1,0.211457

In [2]:
data = pd.get_dummies(df)
data.reset_index(drop=True, inplace=True)
data

,Age,Income,LoanAmount,CreditScore,YearsExperience,LoanApproved,DebtToIncomeRatio,Gender_Female,Gender_Male,Education_Bachelors,Education_High School,Education_Masters,Education_PhD,City_Chicago,City_Houston,City_New York,City_San Francisco,EmploymentType_Salaried,EmploymentType_Self-Employed,EmploymentType_Unemployed
0,56,48353.0,31258.0,675.0,20,0,0.646454,True,False,False,True,False,False,False,True,False,False,False,False,True
1,69,57462.0,23262.0,586.0,6,0,0.404824,False,True,False,True,False,False,False,False,False,True,False,True,False
2,46,44219.0,26530.0,781.0,26,1,0.599968,False,True,False,False,False,True,False,True,False,False,False,True,False
3,60,37034.0,27871.0,500.0,19,0,0.752579,True,False,False,True,False,False,True,False,False,False,False,False,True
4,25,47886.0,18106.0,835.0,13,1,0.378106,False,True,False,False,True,False,False,False,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4425,66,45575.0,32748.0,803.0,39,1,0.718552,True,False,False,False,True,False,False,False,False,True,True,False,False
4426,21,40705.0,15668.0,396.0,34,0,0.384916,True,False,True,False,False,False,False,True,False,False,False,False,True
4427,66,99146.0,9760.0,306.0,14,0,0.098441,False,True,False,False,False,True,False,False,True,False,False,False,True
4428,26,58100.0,18230.0,311.0,10,0,0.313769,True,False,False,True,False,False,False,False,False,True,False,True,False
4429,53,58513.0,12373.0,813.0,23,1,0.211457,False,True,False,False,False,True,False,True,False,False,True,False,False

In [3]:
x_data = data.drop('LoanApproved', axis=1).astype(float).values
y_data = data["LoanApproved"].values

In [4]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 = train_test_split(x_data, y_data, test_size=0.2, random_state=42, stratify=y_data)
len(X_train1), len(X_test1), len(y_train1), len(y_test1)

(3544, 886, 3544, 886)

In [5]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
Xscaled = scaler.fit_transform(X_train1)
Xtscaled = scaler.transform(X_test1)

In [6]:
import tensorflow as tf
X_train = tf.constant(Xscaled, dtype=tf.float32)
X_test = tf.constant(Xtscaled, dtype=tf.float32)
y_train = tf.constant(y_train1, dtype=tf.float32)
y_test = tf.constant(y_test1, dtype=tf.float32)

In [7]:
len(X_train), len(y_train), len(X_test), len(y_test)

(3544, 3544, 886, 886)

In [8]:
from tensorflow.keras import models, layers
input_shape = Xscaled.shape[1]
model = models.Sequential([
    layers.Input(shape=(input_shape,)),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.1),
    layers.Dense(32, activation='relu'),
    layers.Dropout(0.05),
    layers.Dense(1, activation='sigmoid')
])

model.compile(
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.0005),
    loss = "binary_crossentropy",
    metrics = ['accuracy', tf.keras.metrics.Precision(), tf.keras.metrics.Recall()]
    
)

In [9]:

class_weights = {0: 1.0, 1: 1.5} 

history = model.fit(
    X_train, y_train,
    epochs=680,
    batch_size=64,
    validation_data=(X_test, y_test),
    class_weight=class_weights,
    verbose=1
)

Epoch 1/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.7398 - loss: 0.6386 - precision: 0.3058 - recall: 0.0748 - val_accuracy: 0.8138 - val_loss: 0.4163 - val_precision: 0.9107 - val_recall: 0.2417
Epoch 2/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8476 - loss: 0.4716 - precision: 0.7766 - recall: 0.5036 - val_accuracy: 0.8962 - val_loss: 0.3205 - val_precision: 0.7717 - val_recall: 0.8009
Epoch 3/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8809 - loss: 0.3990 - precision: 0.7354 - recall: 0.7791 - val_accuracy: 0.8916 - val_loss: 0.2960 - val_precision: 0.7386 - val_recall: 0.8436
Epoch 4/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8984 - loss: 0.3641 - precision: 0.7739 - recall: 0.8088 - val_accuracy: 0.8928 - val_loss: 0.2897 - val_precision: 0.7339 - val_recall: 0.8626
Epoch 5/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8956 - loss: 0.3507 - precision: 0.7646 - recall: 0.8100 - val_accuracy: 0.8995 - val_loss: 0.2729 - val_precision: 0.7629 - val_recall: 0.8389
Epoch 6/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8939 - loss: 0.3455 - precision: 0.7606 - recall: 0.8076 - val_accuracy: 0.9120 - val_loss: 0.2583 - val_precision: 0.8182 - val_recall: 0.8104
Epoch 7/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9024 - loss: 0.3312 - precision: 0.7857 - recall: 0.8100 - val_accuracy: 0.9063 - val_loss: 0.2610 - val_precision: 0.7832 - val_recall: 0.8389
Epoch 8/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9162 - loss: 0.3092 - precision: 0.8202 - recall: 0.8290 - val_accuracy: 0.9142 - val_loss: 0.2532 - val_precision: 0.8082 - val_recall: 0.8389
Epoch 9/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9120 - loss: 0.3119 - precision: 0.8125 - recall: 0.8183 - val_accuracy: 0.9097 - val_loss: 0.2547 - val_precision: 0.7811 - val_recall: 0.8626
Epoch 10/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9204 - loss: 0.2988 - precision: 0.8310 - recall: 0.8349 - val_accuracy: 0.9187 - val_loss: 0.2492 - val_precision: 0.8174 - val_recall: 0.8483
Epoch 11/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9176 - loss: 0.2965 - precision: 0.8274 - recall: 0.8254 - val_accuracy: 0.9142 - val_loss: 0.2506 - val_precision: 0.7922 - val_recall: 0.8673
Epoch 12/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9190 - loss: 0.2880 - precision: 0.8276 - recall: 0.8325 - val_accuracy: 0.9255 - val_loss: 0.2391 - val_precision: 0.8372 - val_recall: 0.8531
Epoch 13/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9227 - loss: 0.2796 - precision: 0.8318 - recall: 0.8456 - val_accuracy: 0.9300 - val_loss: 0.2307 - val_precision: 0.8599 - val_recall: 0.8436
Epoch 14/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9264 - loss: 0.2750 - precision: 0.8462 - recall: 0.8432 - val_accuracy: 0.9244 - val_loss: 0.2350 - val_precision: 0.8364 - val_recall: 0.8483
Epoch 15/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9354 - loss: 0.2630 - precision: 0.8715 - recall: 0.8539 - val_accuracy: 0.9323 - val_loss: 0.2315 - val_precision: 0.8512 - val_recall: 0.8673
Epoch 16/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9306 - loss: 0.2622 - precision: 0.8590 - recall: 0.8468 - val_accuracy: 0.9323 - val_loss: 0.2292 - val_precision: 0.8545 - val_recall: 0.8626
Epoch 17/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9334 - loss: 0.2646 - precision: 0.8642 - recall: 0.8539 - val_accuracy: 0.9391 - val_loss: 0.2191 - val_precision: 0.8905 - val_recall: 0.8483
Epoch 18/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9374 - loss: 0.2562 - precision: 0.8818 - recall: 0.8504 - val_accuracy: 0.9312 - val_loss: 0.2350 - val_precision: 0.8378 - val_recall: 0.8815
Epoch 19/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9427 - loss: 0.2502 - precision: 0.8911 - recall: 0.8646 - val_accuracy: 0.9334 - val_loss: 0.2237 - val_precision: 0.8585 - val_recall: 0.8626
Epoch 20/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9393 - loss: 0.2495 - precision: 0.8800 - recall: 0.8622 - val_accuracy: 0.9345 - val_loss: 0.2217 - val_precision: 0.8732 - val_recall: 0.8483
Epoch 21/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9410 - loss: 0.2498 - precision: 0.8903 - recall: 0.8575 - val_accuracy: 0.9368 - val_loss: 0.2225 - val_precision: 0.8638 - val_recall: 0.8720
Epoch 22/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9430 - loss: 0.2413 - precision: 0.8912 - recall: 0.8658 - val_accuracy: 0.9413 - val_loss: 0.2154 - val_precision: 0.8841 - val_recall: 0.8673
Epoch 23/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9453 - loss: 0.2306 - precision: 0.8951 - recall: 0.8717 - val_accuracy: 0.9368 - val_loss: 0.2163 - val_precision: 0.8708 - val_recall: 0.8626
Epoch 24/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9416 - loss: 0.2403 - precision: 0.8886 - recall: 0.8622 - val_accuracy: 0.9424 - val_loss: 0.2111 - val_precision: 0.9040 - val_recall: 0.8483
Epoch 25/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9495 - loss: 0.2263 - precision: 0.9139 - recall: 0.8694 - val_accuracy: 0.9379 - val_loss: 0.2218 - val_precision: 0.8611 - val_recall: 0.8815
Epoch 26/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9458 - loss: 0.2347 - precision: 0.8983 - recall: 0.8705 - val_accuracy: 0.9481 - val_loss: 0.2123 - val_precision: 0.8986 - val_recall: 0.8815
Epoch 27/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9453 - loss: 0.2292 - precision: 0.8971 - recall: 0.8694 - val_accuracy: 0.9402 - val_loss: 0.2213 - val_precision: 0.8692 - val_recall: 0.8815
Epoch 28/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9486 - loss: 0.2239 - precision: 0.9054 - recall: 0.8753 - val_accuracy: 0.9470 - val_loss: 0.2057 - val_precision: 0.9059 - val_recall: 0.8673
Epoch 29/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.9478 - loss: 0.2222 - precision: 0.9122 - recall: 0.8634 - val_accuracy: 0.9481 - val_loss: 0.2064 - val_precision: 0.9104 - val_recall: 0.8673
Epoch 30/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9478 - loss: 0.2253 - precision: 0.9021 - recall: 0.8753 - val_accuracy: 0.9413 - val_loss: 0.2050 - val_precision: 0.9077 - val_recall: 0.8389
Epoch 31/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9464 - loss: 0.2231 - precision: 0.8995 - recall: 0.8717 - val_accuracy: 0.9424 - val_loss: 0.2019 - val_precision: 0.9082 - val_recall: 0.8436
Epoch 32/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9486 - loss: 0.2166 - precision: 0.9074 - recall: 0.8729 - val_accuracy: 0.9481 - val_loss: 0.2025 - val_precision: 0.9104 - val_recall: 0.8673
Epoch 33/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9526 - loss: 0.2085 - precision: 0.9255 - recall: 0.8705 - val_accuracy: 0.9436 - val_loss: 0.2111 - val_precision: 0.8779 - val_recall: 0.8863
Epoch 34/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9501 - loss: 0.2161 - precision: 0.9050 - recall: 0.8824 - val_accuracy: 0.9458 - val_loss: 0.2071 - val_precision: 0.9015 - val_recall: 0.8673
Epoch 35/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9526 - loss: 0.2105 - precision: 0.9202 - recall: 0.8765 - val_accuracy: 0.9447 - val_loss: 0.2109 - val_precision: 0.8894 - val_recall: 0.8768
Epoch 36/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9515 - loss: 0.2132 - precision: 0.9075 - recall: 0.8860 - val_accuracy: 0.9492 - val_loss: 0.2019 - val_precision: 0.9235 - val_recall: 0.8578
Epoch 37/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9523 - loss: 0.2041 - precision: 0.9191 - recall: 0.8765 - val_accuracy: 0.9447 - val_loss: 0.2055 - val_precision: 0.9091 - val_recall: 0.8531
Epoch 38/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9546 - loss: 0.1982 - precision: 0.9219 - recall: 0.8836 - val_accuracy: 0.9492 - val_loss: 0.2066 - val_precision: 0.9235 - val_recall: 0.8578
Epoch 39/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9571 - loss: 0.1943 - precision: 0.9259 - recall: 0.8907 - val_accuracy: 0.9470 - val_loss: 0.2052 - val_precision: 0.9059 - val_recall: 0.8673
Epoch 40/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9532 - loss: 0.2042 - precision: 0.9204 - recall: 0.8789 - val_accuracy: 0.9447 - val_loss: 0.2088 - val_precision: 0.8971 - val_recall: 0.8673
Epoch 41/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9537 - loss: 0.1942 - precision: 0.9185 - recall: 0.8836 - val_accuracy: 0.9481 - val_loss: 0.2086 - val_precision: 0.9146 - val_recall: 0.8626
Epoch 42/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9568 - loss: 0.1893 - precision: 0.9280 - recall: 0.8872 - val_accuracy: 0.9470 - val_loss: 0.2088 - val_precision: 0.9184 - val_recall: 0.8531
Epoch 43/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9549 - loss: 0.1937 - precision: 0.9210 - recall: 0.8860 - val_accuracy: 0.9458 - val_loss: 0.2092 - val_precision: 0.9137 - val_recall: 0.8531
Epoch 44/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9591 - loss: 0.1857 - precision: 0.9362 - recall: 0.8884 - val_accuracy: 0.9492 - val_loss: 0.2055 - val_precision: 0.9235 - val_recall: 0.8578
Epoch 45/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9563 - loss: 0.1906 - precision: 0.9288 - recall: 0.8836 - val_accuracy: 0.9481 - val_loss: 0.2062 - val_precision: 0.9231 - val_recall: 0.8531
Epoch 46/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9582 - loss: 0.1883 - precision: 0.9370 - recall: 0.8836 - val_accuracy: 0.9481 - val_loss: 0.2063 - val_precision: 0.9064 - val_recall: 0.8720
Epoch 47/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9571 - loss: 0.1879 - precision: 0.9291 - recall: 0.8872 - val_accuracy: 0.9436 - val_loss: 0.2076 - val_precision: 0.9128 - val_recall: 0.8436
Epoch 48/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9605 - loss: 0.1783 - precision: 0.9398 - recall: 0.8907 - val_accuracy: 0.9458 - val_loss: 0.2198 - val_precision: 0.8900 - val_recall: 0.8815
Epoch 49/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9546 - loss: 0.1809 - precision: 0.9188 - recall: 0.8872 - val_accuracy: 0.9458 - val_loss: 0.2120 - val_precision: 0.8976 - val_recall: 0.8720
Epoch 50/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9574 - loss: 0.1834 - precision: 0.9271 - recall: 0.8907 - val_accuracy: 0.9458 - val_loss: 0.2095 - val_precision: 0.9223 - val_recall: 0.8436
Epoch 51/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9577 - loss: 0.1772 - precision: 0.9282 - recall: 0.8907 - val_accuracy: 0.9481 - val_loss: 0.2144 - val_precision: 0.9146 - val_recall: 0.8626
Epoch 52/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9540 - loss: 0.1809 - precision: 0.9207 - recall: 0.8824 - val_accuracy: 0.9481 - val_loss: 0.2120 - val_precision: 0.9064 - val_recall: 0.8720
Epoch 53/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9568 - loss: 0.1766 - precision: 0.9227 - recall: 0.8931 - val_accuracy: 0.9470 - val_loss: 0.2126 - val_precision: 0.8905 - val_recall: 0.8863
Epoch 54/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9625 - loss: 0.1625 - precision: 0.9393 - recall: 0.9002 - val_accuracy: 0.9470 - val_loss: 0.2102 - val_precision: 0.9316 - val_recall: 0.8389
Epoch 55/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9622 - loss: 0.1754 - precision: 0.9447 - recall: 0.8931 - val_accuracy: 0.9503 - val_loss: 0.2122 - val_precision: 0.9196 - val_recall: 0.8673
Epoch 56/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9577 - loss: 0.1755 - precision: 0.9336 - recall: 0.8848 - val_accuracy: 0.9492 - val_loss: 0.2110 - val_precision: 0.9109 - val_recall: 0.8720
Epoch 57/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9599 - loss: 0.1685 - precision: 0.9353 - recall: 0.8931 - val_accuracy: 0.9481 - val_loss: 0.2146 - val_precision: 0.9064 - val_recall: 0.8720
Epoch 58/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9574 - loss: 0.1790 - precision: 0.9281 - recall: 0.8895 - val_accuracy: 0.9481 - val_loss: 0.2190 - val_precision: 0.9064 - val_recall: 0.8720
Epoch 59/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9602 - loss: 0.1695 - precision: 0.9387 - recall: 0.8907 - val_accuracy: 0.9481 - val_loss: 0.2162 - val_precision: 0.9024 - val_recall: 0.8768
Epoch 60/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9611 - loss: 0.1683 - precision: 0.9389 - recall: 0.8943 - val_accuracy: 0.9470 - val_loss: 0.2098 - val_precision: 0.9316 - val_recall: 0.8389
Epoch 61/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9630 - loss: 0.1551 - precision: 0.9438 - recall: 0.8979 - val_accuracy: 0.9481 - val_loss: 0.2156 - val_precision: 0.9146 - val_recall: 0.8626
Epoch 62/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9616 - loss: 0.1582 - precision: 0.9424 - recall: 0.8931 - val_accuracy: 0.9447 - val_loss: 0.2172 - val_precision: 0.8932 - val_recall: 0.8720
Epoch 63/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9622 - loss: 0.1584 - precision: 0.9436 - recall: 0.8943 - val_accuracy: 0.9458 - val_loss: 0.2183 - val_precision: 0.9015 - val_recall: 0.8673
Epoch 64/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9622 - loss: 0.1523 - precision: 0.9414 - recall: 0.8967 - val_accuracy: 0.9481 - val_loss: 0.2189 - val_precision: 0.9188 - val_recall: 0.8578
Epoch 65/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9644 - loss: 0.1511 - precision: 0.9486 - recall: 0.8990 - val_accuracy: 0.9503 - val_loss: 0.2197 - val_precision: 0.9196 - val_recall: 0.8673
Epoch 66/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9619 - loss: 0.1563 - precision: 0.9435 - recall: 0.8931 - val_accuracy: 0.9503 - val_loss: 0.2177 - val_precision: 0.9154 - val_recall: 0.8720
Epoch 67/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9611 - loss: 0.1534 - precision: 0.9346 - recall: 0.8990 - val_accuracy: 0.9503 - val_loss: 0.2243 - val_precision: 0.9196 - val_recall: 0.8673
Epoch 68/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9580 - loss: 0.1607 - precision: 0.9337 - recall: 0.8860 - val_accuracy: 0.9458 - val_loss: 0.2258 - val_precision: 0.8976 - val_recall: 0.8720
Epoch 69/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9616 - loss: 0.1467 - precision: 0.9413 - recall: 0.8943 - val_accuracy: 0.9458 - val_loss: 0.2264 - val_precision: 0.8976 - val_recall: 0.8720
Epoch 70/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9647 - loss: 0.1520 - precision: 0.9442 - recall: 0.9050 - val_accuracy: 0.9458 - val_loss: 0.2220 - val_precision: 0.9095 - val_recall: 0.8578
Epoch 71/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9653 - loss: 0.1484 - precision: 0.9511 - recall: 0.9002 - val_accuracy: 0.9481 - val_loss: 0.2219 - val_precision: 0.9319 - val_recall: 0.8436
Epoch 72/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9599 - loss: 0.1533 - precision: 0.9342 - recall: 0.8943 - val_accuracy: 0.9458 - val_loss: 0.2279 - val_precision: 0.9179 - val_recall: 0.8483
Epoch 73/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9622 - loss: 0.1493 - precision: 0.9458 - recall: 0.8919 - val_accuracy: 0.9481 - val_loss: 0.2248 - val_precision: 0.9188 - val_recall: 0.8578
Epoch 74/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9636 - loss: 0.1468 - precision: 0.9451 - recall: 0.8990 - val_accuracy: 0.9481 - val_loss: 0.2256 - val_precision: 0.9064 - val_recall: 0.8720
Epoch 75/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9650 - loss: 0.1396 - precision: 0.9476 - recall: 0.9026 - val_accuracy: 0.9503 - val_loss: 0.2284 - val_precision: 0.9154 - val_recall: 0.8720
Epoch 76/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9628 - loss: 0.1395 - precision: 0.9372 - recall: 0.9038 - val_accuracy: 0.9503 - val_loss: 0.2302 - val_precision: 0.9196 - val_recall: 0.8673
Epoch 77/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9622 - loss: 0.1379 - precision: 0.9458 - recall: 0.8919 - val_accuracy: 0.9470 - val_loss: 0.2365 - val_precision: 0.9020 - val_recall: 0.8720
Epoch 78/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9639 - loss: 0.1399 - precision: 0.9463 - recall: 0.8990 - val_accuracy: 0.9492 - val_loss: 0.2329 - val_precision: 0.9109 - val_recall: 0.8720
Epoch 79/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9622 - loss: 0.1461 - precision: 0.9392 - recall: 0.8990 - val_accuracy: 0.9503 - val_loss: 0.2314 - val_precision: 0.9239 - val_recall: 0.8626
Epoch 80/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9647 - loss: 0.1405 - precision: 0.9442 - recall: 0.9050 - val_accuracy: 0.9481 - val_loss: 0.2342 - val_precision: 0.9104 - val_recall: 0.8673
Epoch 81/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9659 - loss: 0.1316 - precision: 0.9445 - recall: 0.9097 - val_accuracy: 0.9515 - val_loss: 0.2371 - val_precision: 0.9286 - val_recall: 0.8626
Epoch 82/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9619 - loss: 0.1415 - precision: 0.9359 - recall: 0.9014 - val_accuracy: 0.9470 - val_loss: 0.2407 - val_precision: 0.9141 - val_recall: 0.8578
Epoch 83/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9659 - loss: 0.1364 - precision: 0.9501 - recall: 0.9038 - val_accuracy: 0.9492 - val_loss: 0.2344 - val_precision: 0.9150 - val_recall: 0.8673
Epoch 84/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9650 - loss: 0.1312 - precision: 0.9432 - recall: 0.9074 - val_accuracy: 0.9481 - val_loss: 0.2354 - val_precision: 0.9188 - val_recall: 0.8578
Epoch 85/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9642 - loss: 0.1368 - precision: 0.9397 - recall: 0.9074 - val_accuracy: 0.9458 - val_loss: 0.2360 - val_precision: 0.9095 - val_recall: 0.8578
Epoch 86/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9659 - loss: 0.1310 - precision: 0.9456 - recall: 0.9086 - val_accuracy: 0.9492 - val_loss: 0.2418 - val_precision: 0.9109 - val_recall: 0.8720
Epoch 87/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9684 - loss: 0.1278 - precision: 0.9517 - recall: 0.9133 - val_accuracy: 0.9481 - val_loss: 0.2393 - val_precision: 0.9104 - val_recall: 0.8673
Epoch 88/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9681 - loss: 0.1256 - precision: 0.9506 - recall: 0.9133 - val_accuracy: 0.9481 - val_loss: 0.2406 - val_precision: 0.9104 - val_recall: 0.8673
Epoch 89/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9642 - loss: 0.1319 - precision: 0.9452 - recall: 0.9014 - val_accuracy: 0.9481 - val_loss: 0.2490 - val_precision: 0.9064 - val_recall: 0.8720
Epoch 90/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9673 - loss: 0.1276 - precision: 0.9459 - recall: 0.9145 - val_accuracy: 0.9470 - val_loss: 0.2473 - val_precision: 0.9100 - val_recall: 0.8626
Epoch 91/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9692 - loss: 0.1176 - precision: 0.9530 - recall: 0.9157 - val_accuracy: 0.9424 - val_loss: 0.2433 - val_precision: 0.9124 - val_recall: 0.8389
Epoch 92/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9715 - loss: 0.1175 - precision: 0.9568 - recall: 0.9216 - val_accuracy: 0.9470 - val_loss: 0.2470 - val_precision: 0.9059 - val_recall: 0.8673
Epoch 93/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9687 - loss: 0.1246 - precision: 0.9540 - recall: 0.9121 - val_accuracy: 0.9481 - val_loss: 0.2461 - val_precision: 0.9146 - val_recall: 0.8626
Epoch 94/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9673 - loss: 0.1166 - precision: 0.9470 - recall: 0.9133 - val_accuracy: 0.9481 - val_loss: 0.2415 - val_precision: 0.9188 - val_recall: 0.8578
Epoch 95/680
56/56 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9661 - loss: 0.1241 - precision: 0.9446 - recall: 0.9109 - val_accuracy: 0.9447 - val_loss: 0.2476 - val_precision: 0.9091 - val_recall: 0.8531
Epoch 96/680

In [15]:
from sklearn.metrics import classification_report, confusion_matrix

predictions = (model.predict(X_test) > 0.5).astype(int)
print(classification_report(y_test, predictions))

28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
              precision    recall  f1-score   support

         0.0       0.96      0.97      0.96       675
         1.0       0.90      0.86      0.88       211

    accuracy                           0.94       886
   macro avg       0.93      0.92      0.92       886
weighted avg       0.94      0.94      0.94       886

In [16]:
model.save('loan_model2.keras')